// Mock data for skin diseases
export const diseases = [
  {
    id: "1",
    name: "Mụn trứng cá",
    description: "Là một tình trạng da xảy ra khi các nang lông bị tắc nghẽn bởi dầu và tế bào da chết, gây ra mụn, đầu đen hoặc đầu trắng.",
    symptoms: ["Mụn", "Đầu đen", "Đầu trắng", "Đỏ da", "Viêm"],
    treatments: ["Retinoid bôi ngoài da", "Kháng sinh", "Peroxide benzoyl", "Acid salicylic"],
    imageUrl: "https://images.unsplash.com/photo-1513165533842-511d7f2bae62?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ đến Trung bình",
  },
  {
    id: "2",
    name: "Viêm da cơ địa",
    description: "Là tình trạng khiến da bạn đỏ và ngứa. Nó phổ biến ở trẻ em nhưng có thể xảy ra ở bất kỳ độ tuổi nào.",
    symptoms: ["Da khô", "Ngứa", "Phát ban đỏ", "Vết tróc vảy", "Sưng"],
    treatments: ["Kem dưỡng ẩm", "Kem corticosteroid", "Thuốc kháng histamine", "Liệu pháp ánh sáng"],
    imageUrl: "https://images.unsplash.com/photo-1579165466741-7f35e4755183?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ đến Nặng",
  },
  {
    id: "3",
    name: "Bệnh vẩy nến",
    description: "Là một rối loạn da khiến các tế bào da phát triển nhanh gấp 10 lần bình thường, dẫn đến những mảng đỏ có vảy trắng.",
    symptoms: ["Mảng đỏ", "Vảy bạc", "Da khô, nứt nẻ", "Ngứa", "Bỏng rát"],
    treatments: ["Corticosteroid bôi ngoài da", "Dẫn xuất Vitamin D", "Liệu pháp ánh sáng", "Biologics"],
    imageUrl: "https://images.unsplash.com/photo-1514672013381-c6d0df1c8b18?q=80&w=500&auto=format&fit=crop",
    severity: "Trung bình đến Nặng",
  },
  {
    id: "4",
    name: "Bệnh hồng ban",
    description: "Là tình trạng da phổ biến gây đỏ và mạch máu dễ nhìn thấy trên khuôn mặt, đôi khi xuất hiện các nốt đỏ nhỏ chứa mủ.",
    symptoms: ["Đỏ mặt", "Nốt đỏ sưng", "Mạch máu dễ thấy", "Vấn đề về mắt"],
    treatments: ["Thuốc bôi ngoài da", "Kháng sinh uống", "Liệu pháp laser"],
    imageUrl: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ đến Trung bình",
  },
  {
    id: "5",
    name: "U ác tính (Melanoma)",
    description: "Là loại ung thư da nghiêm trọng nhất, phát triển trong các tế bào sản xuất melanin, sắc tố tạo màu cho da.",
    symptoms: ["Nốt ruồi không đối xứng", "Biên giới không đều", "Thay đổi màu sắc", "Đường kính lớn hơn 6mm", "Kích thước hoặc hình dạng thay đổi"],
    treatments: ["Phẫu thuật", "Liệu pháp miễn dịch", "Liệu pháp nhắm mục tiêu", "Xạ trị"],
    imageUrl: "https://images.unsplash.com/photo-1577128786741-a94d32b1f2d8?q=80&w=500&auto=format&fit=crop",
    severity: "Nghiêm trọng",
  },
  {
    id: "6",
    name: "Viêm da tiếp xúc",
    description: "Là thuật ngữ chung mô tả tình trạng kích ứng da phổ biến, gây phát ban ngứa và da sưng đỏ.",
    symptoms: ["Ngứa", "Đỏ da", "Sưng", "Da khô", "Mụn nước"],
    treatments: ["Kem corticosteroid", "Thuốc kháng histamine", "Kem dưỡng ẩm", "Tránh các yếu tố gây kích ứng"],
    imageUrl: "https://images.unsplash.com/photo-1612776572997-76cc42e058c3?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ đến Trung bình",
  },
  {
    id: "7",
    name: "Nổi mề đay",
    description: "Các nốt đỏ ngứa xuất hiện do phản ứng của da, thường xuất hiện đột ngột và nhanh chóng biến mất.",
    symptoms: ["Nốt nổi", "Ngứa", "Sưng", "Cảm giác bỏng rát"],
    treatments: ["Thuốc kháng histamine", "Corticosteroid", "Epinephrine (cho phản ứng nghiêm trọng)"],
    imageUrl: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ đến Trung bình",
  },
  {
    id: "8",
    name: "Nấm da (Ringworm)",
    description: "Là một bệnh nhiễm nấm phổ biến gây phát ban đỏ hình vòng, ngứa, dù tên gọi có chữ 'worm' nhưng không phải do giun gây ra.",
    symptoms: ["Phát ban hình vòng", "Vết đỏ vảy", "Ngứa", "Rụng tóc (nếu trên da đầu)"],
    treatments: ["Kem chống nấm", "Thuốc chống nấm dạng uống"],
    imageUrl: "https://images.unsplash.com/photo-1579165466676-450c12e1f8da?q=80&w=500&auto=format&fit=crop",
    severity: "Nhẹ",
  }
];
