// Mock data for skin diseases
export const diseases = [
    {
      id: "1",
      name: "Acne",
      description: "A skin condition that occurs when hair follicles plug with oil and dead skin cells, causing pimples, blackheads, or whiteheads.",
      symptoms: ["Pimples", "Blackheads", "Whiteheads", "Redness", "Inflammation"],
      treatments: ["Topical retinoids", "Antibiotics", "Benzoyl peroxide", "Salicylic acid"],
      imageUrl: "https://images.unsplash.com/photo-1513165533842-511d7f2bae62?q=80&w=500&auto=format&fit=crop",
      severity: "Mild to Moderate",
    },
    {
      id: "2",
      name: "Eczema",
      description: "A condition that makes your skin red and itchy. It's common in children but can occur at any age.",
      symptoms: ["Dry skin", "Itching", "Red rashes", "Scaly patches", "Swelling"],
      treatments: ["Moisturizers", "Corticosteroid creams", "Antihistamines", "Light therapy"],
      imageUrl: "https://images.unsplash.com/photo-1579165466741-7f35e4755183?q=80&w=500&auto=format&fit=crop",
      severity: "Mild to Severe",
    },
    {
      id: "3",
      name: "Psoriasis",
      description: "A skin disorder that causes skin cells to multiply up to 10 times faster than normal, resulting in bumpy red patches covered with white scales.",
      symptoms: ["Red patches", "Silvery scales", "Dry, cracked skin", "Itching", "Burning"],
      treatments: ["Topical corticosteroids", "Vitamin D analogues", "Light therapy", "Biologics"],
      imageUrl: "https://images.unsplash.com/photo-1514672013381-c6d0df1c8b18?q=80&w=500&auto=format&fit=crop",
      severity: "Moderate to Severe",
    },
    {
      id: "4",
      name: "Rosacea",
      description: "A common skin condition that causes redness and visible blood vessels in your face, sometimes producing small, red, pus-filled bumps.",
      symptoms: ["Facial redness", "Swollen red bumps", "Visible blood vessels", "Eye problems"],
      treatments: ["Topical medications", "Oral antibiotics", "Laser therapy"],
      imageUrl: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=500&auto=format&fit=crop",
      severity: "Mild to Moderate",
    },
    {
      id: "5",
      name: "Melanoma",
      description: "The most serious type of skin cancer, developing in the cells that produce melanin, the pigment that gives your skin its color.",
      symptoms: ["Asymmetrical moles", "Irregular borders", "Color changes", "Diameter larger than 6mm", "Evolving size or shape"],
      treatments: ["Surgery", "Immunotherapy", "Targeted therapy", "Radiation therapy"],
      imageUrl: "https://images.unsplash.com/photo-1577128786741-a94d32b1f2d8?q=80&w=500&auto=format&fit=crop",
      severity: "Severe",
    },
    {
      id: "6",
      name: "Dermatitis",
      description: "A general term that describes a common skin irritation, causing an itchy rash and swollen, reddened skin.",
      symptoms: ["Itching", "Redness", "Swelling", "Dry skin", "Blisters"],
      treatments: ["Corticosteroid creams", "Antihistamines", "Moisturizers", "Avoiding triggers"],
      imageUrl: "https://images.unsplash.com/photo-1612776572997-76cc42e058c3?q=80&w=500&auto=format&fit=crop",
      severity: "Mild to Moderate",
    },
    {
      id: "7",
      name: "Hives",
      description: "Red, itchy welts that result from a skin reaction, often appearing suddenly and resolving quickly.",
      symptoms: ["Raised welts", "Itching", "Swelling", "Burning sensation"],
      treatments: ["Antihistamines", "Corticosteroids", "Epinephrine (for severe reactions)"],
      imageUrl: "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?q=80&w=500&auto=format&fit=crop",
      severity: "Mild to Moderate",
    },
    {
      id: "8",
      name: "Ringworm",
      description: "A common fungal infection that causes a red, circular, itchy rash, despite its name, it's not caused by a worm.",
      symptoms: ["Ring-shaped rash", "Red, scaly patches", "Itching", "Hair loss (if on scalp)"],
      treatments: ["Antifungal creams", "Oral antifungal medications"],
      imageUrl: "https://images.unsplash.com/photo-1579165466676-450c12e1f8da?q=80&w=500&auto=format&fit=crop",
      severity: "Mild",
    }
  ];